#ifndef MINI_OS_PHASE0_LIBSSH2_CONFIG_H
#define MINI_OS_PHASE0_LIBSSH2_CONFIG_H

#define HAVE_SNPRINTF 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_POLL 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_UIO_H 1

#define LIBSSH2_NO_MD5 1
#define LIBSSH2_NO_MD5_PEM 1
#define LIBSSH2_NO_HMAC_RIPEMD 1
#define LIBSSH2_NO_RSA 1
#define LIBSSH2_NO_RSA_SHA1 1
#define LIBSSH2_NO_AES_CBC 1
#define LIBSSH2_NO_BLOWFISH 1
#define LIBSSH2_NO_RC4 1
#define LIBSSH2_NO_CAST 1
#define LIBSSH2_NO_3DES 1
#define LIBSSH2_NO_DEPRECATED 1

#endif
